Repository Nickrsl/goservice, pull requests merged in 2023-09, with the labels that each got.

#14 config: configuração das variáveis de ambiente
  src/main/resources/application.properties
Labels: enhancement

#18 Criação do fragmento footer
  src/main/resources/templates/agendaPrestador.html
  src/main/resources/templates/agendarServico.html
  src/main/resources/templates/alterarSenha.html
  src/main/resources/templates/dadosCliente.html
  src/main/resources/templates/dadosPrestador.html
  src/main/resources/templates/dashboard.html
  src/main/resources/templates/editarServico.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/historicoCliente.html
  src/main/resources/templates/home.html
  src/main/resources/templates/servicosAdmin.html
  src/main/resources/templates/usuariosAdmin.html
Labels: enhancement

#20 feat: Populacao para criacao de dados na tabela
  mysql/POPULATE.sql
Labels: enhancement

#23 feat: criação de uma query que busca a quantidade de agendamentos por status.
  src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
  src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java
  src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
Labels: enhancement

#24 Aplicação dos logos no cabeçalho, rodape, login e cadastro
  src/main/resources/templates/cadastroCliente.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/login.html
Labels: enhancement

#25 Criação dos cards publicitarios na home
  src/main/resources/templates/home.html
Labels: enhancement

#29 Criação da consulta de usuarios por pagina
  src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java
  src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
Labels: enhancement

#30 Criação da consulta de servicos de forma paginada
  src/main/java/com/soulcode/goserviceapp/repository/ServicoRepository.java
  src/main/java/com/soulcode/goserviceapp/service/ServicoService.java
Labels: enhancement

#33 Habilitado a possibilidade de adicionar endereço
  mysql/POPULATE.sql
  src/main/java/com/soulcode/goserviceapp/domain/Administrador.java
  src/main/java/com/soulcode/goserviceapp/domain/Cliente.java
  src/main/java/com/soulcode/goserviceapp/domain/Endereco.java
  src/main/java/com/soulcode/goserviceapp/domain/Prestador.java
  src/main/java/com/soulcode/goserviceapp/domain/Usuario.java
  src/main/java/com/soulcode/goserviceapp/repository/EnderecoRepository.java
  src/main/java/com/soulcode/goserviceapp/service/ClienteService.java
  src/main/java/com/soulcode/goserviceapp/service/EnderecoService.java
  src/main/java/com/soulcode/goserviceapp/service/PrestadorService.java
  src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
Labels: enhancement

#36 feat: #35 Alteracao de endereco do usuario
  src/main/java/com/soulcode/goserviceapp/repository/EnderecoRepository.java
Labels: documentation, enhancement

#38 Add no view os campos para alterar o endereço
  src/main/resources/templates/dadosCliente.html
  src/main/resources/templates/dadosPrestador.html
  src/main/resources/templates/fragments/header.html
Labels: enhancement

#39 Melhorias na validação dos dados no formulário.
  src/main/resources/static/js/script.js
  src/main/resources/templates/agendarServico.html
  src/main/resources/templates/alterarSenha.html
  src/main/resources/templates/cadastroCliente.html
  src/main/resources/templates/dadosCliente.html
  src/main/resources/templates/dadosPrestador.html
  src/main/resources/templates/editarServico.html
  src/main/resources/templates/login.html
  src/main/resources/templates/servicosAdmin.html
  src/main/resources/templates/usuariosAdmin.html
Labels: enhancement

#40 termocondicoes
  src/main/java/com/soulcode/goserviceapp/config/SecurityConfig.java
  src/main/java/com/soulcode/goserviceapp/controller/HomeController.java
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/politica.html
  src/main/resources/templates/termoCondicoes.html
Labels: enhancement

#45 feat: criação do gráfico de usuários por perfil no painel administrativo
  src/main/resources/templates/dashboard.html
Labels: enhancement

#48 Feature/criacao carrossel publicitario
  src/main/resources/static/css/main.css
  src/main/resources/templates/home.html
Labels: enhancement

#49 Darkmode e lightmode
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
Labels: enhancement

#50 Criação do filtro de busca na tabela de serviços em admin
  src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
  src/main/java/com/soulcode/goserviceapp/repository/ServicoRepository.java
  src/main/java/com/soulcode/goserviceapp/service/ServicoService.java
  src/main/resources/templates/servicosAdmin.html
Labels: enhancement

#51 feat: criação do gráfico de agendamentos por status no painel administrativo
  src/main/resources/templates/dashboard.html
Labels: enhancement

#53 feat: caixa de dialogo para detalhes de cliente na agenda dos prestadores.
  src/main/resources/templates/agendaPrestador.html
Labels: enhancement

#54 feat: caixa de dialogo para detalhes de prestador na tabela de histórico
  src/main/resources/templates/historicoCliente.html
Labels: enhancement

#56 feat: cacheamento para busca de dados de usuários na área administrativa
  src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
Labels: enhancement

#59 bug: refazer os métodos/queries que buscam o número de agendamento por status e usuário por perfil
  src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
  src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java
  src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java
  src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
  src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
  src/main/resources/templates/dashboard.html
Labels: bug

#60 firebase completo
  src/main/java/com/soulcode/goserviceapp/controller/FotoPerfilController.java
  src/main/java/com/soulcode/goserviceapp/domain/Cliente.java
  src/main/java/com/soulcode/goserviceapp/domain/Usuario.java
  src/main/java/com/soulcode/goserviceapp/repository/AdminRepository.java
  src/main/java/com/soulcode/goserviceapp/service/AdminService.java
  src/main/java/com/soulcode/goserviceapp/service/ClienteService.java
  src/main/java/com/soulcode/goserviceapp/service/PrestadorService.java
  src/main/resources/static/js/script.js
  src/main/resources/templates/dadosCliente.html
  src/main/resources/templates/dadosPrestador.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/layout.html
Labels: enhancement

#61 Feature/faq
  mysql/POPULATE.sql
  src/main/java/com/soulcode/goserviceapp/config/CacheConfig.java
  src/main/java/com/soulcode/goserviceapp/config/SecurityConfig.java
  src/main/java/com/soulcode/goserviceapp/controller/HomeController.java
  src/main/java/com/soulcode/goserviceapp/domain/Cliente.java
  src/main/resources/static/css/main.css
  src/main/resources/templates/dadosPrestador.html
  src/main/resources/templates/faq.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/politica.html
  src/main/resources/templates/termoCondicoes.html
Labels: enhancement

#63 Lombok Feito com sucesso
  pom.xml
  src/main/java/com/soulcode/goserviceapp/controller/RestApiController.java
  src/main/java/com/soulcode/goserviceapp/domain/Administrador.java
  src/main/java/com/soulcode/goserviceapp/domain/Agendamento.java
  src/main/java/com/soulcode/goserviceapp/domain/Cliente.java
  src/main/java/com/soulcode/goserviceapp/domain/Endereco.java
  src/main/java/com/soulcode/goserviceapp/domain/Prestador.java
  src/main/java/com/soulcode/goserviceapp/domain/Servico.java
  src/main/java/com/soulcode/goserviceapp/domain/Usuario.java
  src/main/java/com/soulcode/goserviceapp/domain/UsuarioLog.java
Labels: enhancement
